package com.zhpush.client.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhpush.client.pojo.MixPushMessage;

import com.zhpush.client.db.MixPushMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mixPushMessageDaoConfig;

    private final MixPushMessageDao mixPushMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mixPushMessageDaoConfig = daoConfigMap.get(MixPushMessageDao.class).clone();
        mixPushMessageDaoConfig.initIdentityScope(type);

        mixPushMessageDao = new MixPushMessageDao(mixPushMessageDaoConfig, this);

        registerDao(MixPushMessage.class, mixPushMessageDao);
    }
    
    public void clear() {
        mixPushMessageDaoConfig.clearIdentityScope();
    }

    public MixPushMessageDao getMixPushMessageDao() {
        return mixPushMessageDao;
    }

}
